/**
 * Expo's default Babel config, with one addition.
 *
 * `src/module_bindings/` is generated by `spacetime generate` and uses TypeScript's
 * `declare field: Type` class syntax. babel-preset-expo hardcodes @babel/plugin-transform-typescript
 * without `allowDeclareFields` and offers no option to pass it, so the web bundle fails on generated
 * code we do not control. This override registers the plugin for .ts/.tsx with that flag on; config
 * plugins run before preset plugins, so this one wins.
 */
module.exports = function babelConfig(api) {
  api.cache(true);
  return {
    presets: ["babel-preset-expo"],
    // Function tests, not RegExp: Metro invokes Babel without a filename on some paths, and a
    // pattern test throws there. This is why the preset itself uses predicates.
    overrides: [
      {
        test: (filename) => !!filename && filename.endsWith(".ts"),
        plugins: [
          [require("@babel/plugin-transform-typescript"), { isTSX: false, allowNamespaces: true, allowDeclareFields: true }],
        ],
      },
      {
        test: (filename) => !!filename && filename.endsWith(".tsx"),
        plugins: [
          [require("@babel/plugin-transform-typescript"), { isTSX: true, allowNamespaces: true, allowDeclareFields: true }],
        ],
      },
    ],
  };
};
