const { defineConfig } = require("eslint/config");
const expoConfig = require("eslint-config-expo/flat");

module.exports = defineConfig([
  // A lone `ignores` is a global ignore; listing it alongside `rules` below would only scope it to
  // that one config object. src/module_bindings is generated by `spacetime generate`.
  { ignores: ["src/module_bindings/**"] },
  expoConfig,
  {
    ignores: ["dist/**"],
    rules: {
      "import/no-unresolved": "off",
      "import/namespace": "off",
      "import/no-duplicates": "off"
    },
  },
]);
