// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  mode: __t.string(),
  player0: __t.identity().name("player_0"),
  player1: __t.identity().name("player_1"),
  name0: __t.string().name("name_0"),
  name1: __t.string().name("name_1"),
  p0Cells: __t.byteArray().name("p_0_cells"),
  p1Cells: __t.byteArray().name("p_1_cells"),
  neutral0: __t.u8().name("neutral_0"),
  neutral1: __t.u8().name("neutral_1"),
  turn: __t.u8(),
  turnNumber: __t.u32().name("turn_number"),
  winner: __t.i8(),
  endReason: __t.string().name("end_reason"),
  clock0Ms: __t.i64().name("clock_0_ms"),
  clock1Ms: __t.i64().name("clock_1_ms"),
  chargedAt: __t.timestamp().name("charged_at"),
  reconnectBy0: __t.i64().name("reconnect_by_0"),
  reconnectBy1: __t.i64().name("reconnect_by_1"),
  ratingBefore0: __t.i32().name("rating_before_0"),
  ratingBefore1: __t.i32().name("rating_before_1"),
  ratingAfter0: __t.i32().name("rating_after_0"),
  ratingAfter1: __t.i32().name("rating_after_1"),
  startedAt: __t.timestamp().name("started_at"),
  finishedAt: __t.option(__t.timestamp()).name("finished_at"),
});
