// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  gameId: __t.u64().name("game_id"),
  mode: __t.string(),
  reason: __t.string(),
  winner: __t.option(__t.identity()),
  loser: __t.option(__t.identity()),
  winnerName: __t.string().name("winner_name"),
  loserName: __t.string().name("loser_name"),
  moves: __t.u32(),
  winnerClockMs: __t.i64().name("winner_clock_ms"),
  loserClockMs: __t.i64().name("loser_clock_ms"),
  winnerRatingBefore: __t.i32().name("winner_rating_before"),
  winnerRatingAfter: __t.i32().name("winner_rating_after"),
  loserRatingBefore: __t.i32().name("loser_rating_before"),
  loserRatingAfter: __t.i32().name("loser_rating_after"),
  startedAt: __t.timestamp().name("started_at"),
  finishedAt: __t.timestamp().name("finished_at"),
});
