// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  username: __t.string(),
  usernameKey: __t.string().name("username_key"),
  avatarStyle: __t.string().name("avatar_style"),
  avatarSeed: __t.string().name("avatar_seed"),
  rating: __t.f64(),
  deviation: __t.f64(),
  volatility: __t.f64(),
  wins: __t.u32(),
  losses: __t.u32(),
  games: __t.u32(),
  ratedAt: __t.timestamp().name("rated_at"),
  online: __t.bool(),
  guest: __t.bool(),
  createdAt: __t.timestamp().name("created_at"),
  lastSeen: __t.timestamp().name("last_seen"),
});
