// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const ActiveGame = __t.object("ActiveGame", {
  identity: __t.identity(),
  gameId: __t.u64(),
});
export type ActiveGame = __Infer<typeof ActiveGame>;

export const Connection = __t.object("Connection", {
  connectionId: __t.connectionId(),
  identity: __t.identity(),
  connectedAt: __t.timestamp(),
});
export type Connection = __Infer<typeof Connection>;

export const FriendEdge = __t.object("FriendEdge", {
  id: __t.u64(),
  owner: __t.identity(),
  other: __t.identity(),
  state: __t.u8(),
  createdAt: __t.timestamp(),
});
export type FriendEdge = __Infer<typeof FriendEdge>;

export const Game = __t.object("Game", {
  id: __t.u64(),
  mode: __t.string(),
  player0: __t.identity(),
  player1: __t.identity(),
  name0: __t.string(),
  name1: __t.string(),
  p0Cells: __t.byteArray(),
  p1Cells: __t.byteArray(),
  neutral0: __t.u8(),
  neutral1: __t.u8(),
  turn: __t.u8(),
  turnNumber: __t.u32(),
  winner: __t.i8(),
  endReason: __t.string(),
  clock0Ms: __t.i64(),
  clock1Ms: __t.i64(),
  chargedAt: __t.timestamp(),
  reconnectBy0: __t.i64(),
  reconnectBy1: __t.i64(),
  ratingBefore0: __t.i32(),
  ratingBefore1: __t.i32(),
  ratingAfter0: __t.i32(),
  ratingAfter1: __t.i32(),
  startedAt: __t.timestamp(),
  finishedAt: __t.option(__t.timestamp()),
});
export type Game = __Infer<typeof Game>;

export const GameTimer = __t.object("GameTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type GameTimer = __Infer<typeof GameTimer>;

export const Leaderboard = __t.object("Leaderboard", {});
export type Leaderboard = __Infer<typeof Leaderboard>;

export const Match = __t.object("Match", {
  id: __t.u64(),
  gameId: __t.u64(),
  mode: __t.string(),
  reason: __t.string(),
  winner: __t.option(__t.identity()),
  loser: __t.option(__t.identity()),
  winnerName: __t.string(),
  loserName: __t.string(),
  moves: __t.u32(),
  winnerClockMs: __t.i64(),
  loserClockMs: __t.i64(),
  winnerRatingBefore: __t.i32(),
  winnerRatingAfter: __t.i32(),
  loserRatingBefore: __t.i32(),
  loserRatingAfter: __t.i32(),
  startedAt: __t.timestamp(),
  finishedAt: __t.timestamp(),
});
export type Match = __Infer<typeof Match>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  username: __t.string(),
  usernameKey: __t.string(),
  avatarStyle: __t.string(),
  avatarSeed: __t.string(),
  rating: __t.f64(),
  deviation: __t.f64(),
  volatility: __t.f64(),
  wins: __t.u32(),
  losses: __t.u32(),
  games: __t.u32(),
  ratedAt: __t.timestamp(),
  online: __t.bool(),
  guest: __t.bool(),
  createdAt: __t.timestamp(),
  lastSeen: __t.timestamp(),
});
export type Player = __Infer<typeof Player>;

export const Preview = __t.object("Preview", {
  gameId: __t.u64(),
  seat: __t.u8(),
  drawn: __t.byteArray(),
  candidate: __t.byteArray(),
  neutral: __t.i8(),
  destination: __t.i8(),
  updatedAt: __t.timestamp(),
});
export type Preview = __Infer<typeof Preview>;

export const QueueEntry = __t.object("QueueEntry", {
  identity: __t.identity(),
  mode: __t.string(),
  rating: __t.i32(),
  queuedAt: __t.timestamp(),
});
export type QueueEntry = __Infer<typeof QueueEntry>;

export const QueueTimer = __t.object("QueueTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type QueueTimer = __Infer<typeof QueueTimer>;

