// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AcceptFriendReducer from "../accept_friend_reducer";
import BlockFriendReducer from "../block_friend_reducer";
import ClearPreviewReducer from "../clear_preview_reducer";
import DeleteAccountReducer from "../delete_account_reducer";
import DequeueReducer from "../dequeue_reducer";
import EnqueueReducer from "../enqueue_reducer";
import ForfeitReducer from "../forfeit_reducer";
import PlayMoveReducer from "../play_move_reducer";
import RemoveFriendReducer from "../remove_friend_reducer";
import SendFriendRequestReducer from "../send_friend_request_reducer";
import SetAvatarReducer from "../set_avatar_reducer";
import SetPreviewReducer from "../set_preview_reducer";
import SetProfileReducer from "../set_profile_reducer";

export type AcceptFriendParams = __Infer<typeof AcceptFriendReducer>;
export type BlockFriendParams = __Infer<typeof BlockFriendReducer>;
export type ClearPreviewParams = __Infer<typeof ClearPreviewReducer>;
export type DeleteAccountParams = __Infer<typeof DeleteAccountReducer>;
export type DequeueParams = __Infer<typeof DequeueReducer>;
export type EnqueueParams = __Infer<typeof EnqueueReducer>;
export type ForfeitParams = __Infer<typeof ForfeitReducer>;
export type PlayMoveParams = __Infer<typeof PlayMoveReducer>;
export type RemoveFriendParams = __Infer<typeof RemoveFriendReducer>;
export type SendFriendRequestParams = __Infer<typeof SendFriendRequestReducer>;
export type SetAvatarParams = __Infer<typeof SetAvatarReducer>;
export type SetPreviewParams = __Infer<typeof SetPreviewReducer>;
export type SetProfileParams = __Infer<typeof SetProfileReducer>;

